name: avatar_maker
description: A light-weight and highly customizable SVG avatar library for
  Flutter apps. Provides a Customizer Widget, CircleAvatar and other utility
  functions that are ready-to-use.
version: 0.0.0
homepage: https://github.com/RoadTripMoustache/avatar_maker

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10
  get: ^4.6.6
  shared_preferences: ^2.2.3
dev_dependencies:
  analyzer: 6.4.0
  build_runner: ^2.4.11
  flutter_gen: ^5.5.0+1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2

flutter:
  assets:
    - assets/icons/
